site_name: PicoADK Documentation

nav:
    - 'index.md'
    - 'getting_started.md'
    - 'hardware_reference.md'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - c
        - cpp
        - bash
